---
- hosts: 127.0.0.1

  vars:
    - bucket_name: 
    - repo_url: 

  tasks:
    - name: pip3 install packages
      pip:
        name: "{{ item }}"
        state: latest
      become: yes
      become_user: root
      with_items:
        - virtualenv
        - boto

    - name: add lowband_cam group
      group:
        name: lowband_cam
        state: present
      become: yes
      become_user: root

    - name: add lowband_cam01 user
      user:
        name: lowband_cam01
        group: lowband_cam
        shell: /bin/bash
        state: present
      become: yes
      become_user: root

    - name: git pull lowband-cam
      git:
        repo: "{{ repo_url }}"
        dest: ~/lowband-cam/
        version: development
        force: yes
        update: yes
      become: yes
      become_user: lowband_cam01

    - name: create virtualenv ~/lowband-cam/venv
      command: python3 -m venv ~/lowband-cam/venv
      become: yes
      become_user: lowband_cam01

    - name: pip3 install awscli
      pip: 
        name: awscli 
        virtualenv: ~/lowband-cam/venv
        state: latest
      become: yes
      become_user: lowband_cam01

    - name: pip3 install lowband-cam requirements
      pip: 
        requirements: ~/lowband-cam/lowband_cam/requirements.txt
        virtualenv: ~/lowband-cam/venv
        state: latest
      become: yes
      become_user: lowband_cam01

    - name: get config from S3
      s3:
        bucket: "{{ bucket_name }}"
        object: /config/config.ini
        dest: ~/lowband-cam/config/config.ini
        mode: get
      become: yes
      become_user: lowband_cam01

    - name: schedule cron for lowband-cam
      cron:
        name: run lowband cam application
        minute: "*/3"
        job: "source ~/lowband-cam/venv/bin/activate && cd ~/lowband-cam && python -m lowband_cam.cam"
      become: yes
      become_user: lowband_cam01

    - name: schedule this playbook to run periodically
      cron:
        name: run lowband cam playbook
        hour: "*"
        job: ansible-playbook ~/lowband-cam/lowband_cam/ansible/playbook-setup-lowband-cam.yml --extra-vars "repo_url={{ repo_url }} bucket_name={{ bucket_name }}"
      become: yes
      become_user: root

    - name: image cleanup - get files older than 30 days
      find:
        paths: ~/lowband-cam/images
        age: 30d 
      register: old_images
      become: yes
      become_user: lowband_cam01

    - name: 
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_images.files }}"
      become: yes
      become_user: lowband_cam01
